### PR TITLE
An import script for official boundaries for Argentina

### PR DESCRIPTION
**Pull request by mhl**

### CODE REVIEW

**Comment by martinszy** [comment]
Hi, I have tried to run it in a newly configured mapit instance and this is the output:

    # ./manage.py mapit_ar_import_boundaries   --provincias=argentina_data/provincias.shp --    departamentos=argentina_data/departamentos.shp
    Traceback (most recent call last):
      File "./manage.py", line 10, in <module>
        execute_from_command_line(sys.argv)
      File "/root/mapit/.venv/local/lib/python2.7/site-packages/django/core/management/__init__.py",     line 338, in execute_from_command_line
        utility.execute()
      File "/root/mapit/.venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 330, in execute
        self.fetch_command(subcommand).run_from_argv(self.argv)
      File "/root/mapit/.venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 390, in run_from_argv
        self.execute(*args, **cmd_options)
      File "/root/mapit/.venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 441, in execute
        output = self.handle(*args, **options)
      File "/root/mapit/.venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 657, in handle
        return self.handle_noargs(**options)
      File "/root/mapit/mapit_ar/management/commands/mapit_ar_import_boundaries.py", line 66, in handle_noargs
        raise Exception("There's no inactive generation for the import")
    Exception: There's no inactive generation for the import

**Comment by martinszy** [comment]
Second error
    # ./manage.py mapit_ar_import_boundaries   --provincias=argentina_data/provincias.shp --departamentos=argentina_data/departamentos.shp
    Traceback (most recent call last):
      File "./manage.py", line 10, in <module>
        execute_from_command_line(sys.argv)
      File "/root/mapit/.venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
        utility.execute()
      File "/root/mapit/.venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 330, in execute
        self.fetch_command(subcommand).run_from_argv(self.argv)
      File "/root/mapit/.venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 390, in run_from_argv
        self.execute(*args, **cmd_options)
      File "/root/mapit/.venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 441, in execute
        output = self.handle(*args, **options)
      File "/root/mapit/.venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 657, in handle
        return self.handle_noargs(**options)
      File "/root/mapit/mapit_ar/management/commands/mapit_ar_import_boundaries.py", line 68, in handle_noargs
        country = Country.objects.get(code='A')
      File "/root/mapit/.venv/local/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
        return getattr(self.get_queryset(), name)(*args, **kwargs)
      File "/root/mapit/.venv/local/lib/python2.7/site-packages/django/db/models/query.py", line 334, in get
        self.model._meta.object_name
    mapit.models.DoesNotExist: Country matching query does not exist.

**Comment by mhl** [comment]
You'll need to run:

    ./manage.py loaddata mapit_ar/fixtures/argentina.json

... before running the import command.

**Comment by martinszy** [comment]
# ./manage.py mapit_ar_import_boundaries --provincias=argentina_data/provincias.shp --departamentos=argentina_data/departamentos.shp
DoesNotExist: Country matching query does not exist. Lookup parameters were {'code': 'AR'}

**Comment by mhl** [comment]
Have you made a local change to the script?

That error suggests that it's looking up the wrong country code - it should just be 'A', from this line: https://github.com/mysociety/mapit/pull/188/files#diff-4600dcc4127462d41cfed68b9cd76ea0R68

And the country with that code is created from here in the fixture: https://github.com/mysociety/mapit/blob/argentina/mapit_ar/fixtures/argentina.json#L2

**Comment by dracos** [comment]
Very out of date, don't think needed any longer; could be in own repo.

**Pull request closed without merging**
