### PR TITLE
Add pricing info to the licensing page

### LINKED ISSUE #181: Add some pricing info to the licensing page

### PR DESCRIPTION
**Pull request by stevenday**
This is mostly copied from the new text on the TWFY page, along with some
re-arrangements to match the general tone of that such as moving the techy
stuff lower down.

@abimysoc, @MyfanwyNixon - could you check this over too? (I'll add a
screenshot in a second).

Closes #181

### CODE REVIEW

**Comment by stevenday** [comment]
screen shot 2015-04-14 at 10 10 47

**Comment by MyfanwyNixon** [comment]
All good - but I think we need to be more explicit about which of our 'helpful' services would be paid for. 
The following points need 'prices start at', 'for a cost of' or (if applicable) 'this service is free' attached to them IMO:

"We can set you up with a dedicated service"
"Some organisations prefer to install their own internal version of MapIt. We are happy to help with this. Depending on your needs, we can advise your technical team on how to do this, or our developers can install it for you"
One off data range services - "we can do this for you quickly and easily"

**Comment by abimysoc** [comment]
IAWMyf.

"our developers can install it for you (for a fee)"
"we can do this for you - ask us for a quote" (I've removed "quickly and easily" here because pricing is based on time spent, not on difficulty.)
"We can set you up with a dedicated service" already mentions "paid" earlier in the paragraph so I think it's implied there that there'd be a cost; if someone is interested in lifting the rate limit they'd have to talk to us about buying a licence anyway.

Plus I would also request that the 'Technical queries' section is put back at the top of the page, where it is currently.

**Comment by BenJam** [comment]
might be worth having a >500,000 option of 'get in touch'.

**Comment by stevenday** [comment]
Sorry, realised that I never added a second screenshot - here's how it looks now:

screen shot 2015-04-17 at 11 26 49

**Comment by abimysoc** [comment]
https://github.com/mysociety/theyworkforyou/pull/814#issuecomment-94020130 also applies here.

**Comment by stevenday** [comment]
This is all rebased up and ready to go I think - @dracos, can you give it a look over before I merge and deploy?

**Comment by dracos** [comment]
If I wanted to be really picky, given you've used nice typography elsewhere, I'd ask for an en-dash rather than a hyphen where you've used one ;) Looks fine.

**Comment by stevenday** [comment]
@dracos, nice dashes everywhere as requested - ta :)

**Pull request merged**
