### PR TITLE
Add import script for NHS England CCG areas

### PR DESCRIPTION
**Pull request by chris48s**
As with the Police Force boundaries (see pull request #73), NHS CCG boundaries for England are available as open data, but they aren't formatted in such a way that they import nicely into MapIt.
This import script solves that problem, importing the CCG boundaries cleanly.
This may be useful to pull into master for users self-hosting, or could be useful for mapit uk if you decide to publish the CCG boundaries (as raised in issue #74).

### CODE REVIEW

**Comment by dracos** [comment]
I realise this copies the previous PR you mention, but is there a reason this command isn't a subclass of the mapit_import Command? I can't obviously see a reason why it has to use call_command and duplicate a lot of options/set up code, but I may well have missed something.

**Comment by chris48s** [comment]
Commits have been tidied as requested. I'll have a go at refactoring this based on your suggestions and get back to you with an updated pull request.

**Comment by chris48s** [comment]
I've refactored this to extend mapit_import, as requested. I've constructed an appropriate option_list by slicing mapit_import's option_list tuple. This solution is more succinct then redefining it but the downside to this is that adding or removing elements from the start or in the middle of mapit_import's option_list tuple would require updating the line:
```
    option_list = mapit_import.Command.option_list[:7] + \
                  mapit_import.Command.option_list[8:11] + \
                  mapit_import.Command.option_list[15:20]
```
accordingly.
Just something to be aware of there.

**Comment by dracos** [comment]
Thanks, that's a bit less code :) A suggestion for your downside - see how what I've done in https://github.com/mysociety/mapit/commit/3175d648060e9f0c3c0f966a88c0fd86db43cc4b uses `create_parser` to set defaults instead, doing it that way (or other similar things, perhaps `remove_option`) might save you having to do a slice, and be more robust.

**Comment by chris48s** [comment]
No problem - updated as requested.

**Comment by torotil** [comment]
I think this is outdated as the current CCG boundary files can be imported with the generic import command.

**Comment by chris48s** [comment]
Agreed :+1:  Closing this and tidying up some other forgotten PRs that went nowhere

**Pull request closed without merging**
